# Generated by Django 4.2.7 on 2026-03-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="financialprofile",
            name="person_home_ownership",
            field=models.CharField(
                choices=[
                    ("RENT", "Rent"),
                    ("OWN", "Own"),
                    ("MORTGAGE", "Mortgage"),
                    ("OTHER", "Other"),
                ],
                help_text="e.g. RENT, OWN, MORTGAGE",
                max_length=20,
            ),
        ),
    ]
