# Generated by Django 4.2.7 on 2026-03-14 02:26

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_financialprofile_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialprofile",
            name="income_proof_status",
            field=models.CharField(
                choices=[
                    ("NOT_SUBMITTED", "Not Submitted"),
                    ("PENDING", "Pending Review"),
                    ("VERIFIED", "Verified"),
                    ("REJECTED", "Rejected"),
                ],
                default="NOT_SUBMITTED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="financialprofile",
            name="income_proof_uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financialprofile",
            name="salary_slip",
            field=models.FileField(
                blank=True,
                help_text="Salary slip or income proof document uploaded by the applicant",
                null=True,
                upload_to=users.models.salary_slip_upload_path,
            ),
        ),
    ]
