# Generated by Django 4.2.7 on 2026-03-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_is_verified_customuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pan_number",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
