# Generated by Django 4.2.7 on 2026-04-01 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_customuser_pan_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dob", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("residential_address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AP", "Andhra Pradesh"),
                            ("AR", "Arunachal Pradesh"),
                            ("AS", "Assam"),
                            ("BR", "Bihar"),
                            ("CT", "Chhattisgarh"),
                            ("GA", "Goa"),
                            ("GJ", "Gujarat"),
                            ("HR", "Haryana"),
                            ("HP", "Himachal Pradesh"),
                            ("JK", "Jammu and Kashmir"),
                            ("JH", "Jharkhand"),
                            ("KA", "Karnataka"),
                            ("KL", "Kerala"),
                            ("MP", "Madhya Pradesh"),
                            ("MH", "Maharashtra"),
                            ("MN", "Manipur"),
                            ("ML", "Meghalaya"),
                            ("MZ", "Mizoram"),
                            ("NL", "Nagaland"),
                            ("OR", "Odisha"),
                            ("PB", "Punjab"),
                            ("RJ", "Rajasthan"),
                            ("SK", "Sikkim"),
                            ("TN", "Tamil Nadu"),
                            ("TG", "Telangana"),
                            ("TR", "Tripura"),
                            ("UP", "Uttar Pradesh"),
                            ("UT", "Uttarakhand"),
                            ("WB", "West Bengal"),
                            ("AN", "Andaman and Nicobar Islands"),
                            ("CH", "Chandigarh"),
                            ("DN", "Dadra and Nagar Haveli"),
                            ("DD", "Daman and Diu"),
                            ("DL", "Delhi"),
                            ("LD", "Lakshadweep"),
                            ("PY", "Puducherry"),
                        ],
                        max_length=2,
                    ),
                ),
                ("pin_code", models.CharField(max_length=6)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("SALARIED", "Salaried"),
                            ("SELF_EMPLOYED", "Self-employed"),
                            ("BUSINESS", "Business"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "employer_business_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "annual_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "loan_amount_requested",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("loan_purpose", models.CharField(max_length=100)),
                (
                    "existing_emis",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("num_dependants", models.IntegerField(default=0)),
                ("has_residential_property", models.BooleanField(default=False)),
                ("has_commercial_property", models.BooleanField(default=False)),
                ("has_agricultural_land", models.BooleanField(default=False)),
                ("has_vehicle", models.BooleanField(default=False)),
                ("has_gold_jewellery", models.BooleanField(default=False)),
                ("has_fixed_deposits", models.BooleanField(default=False)),
                ("aadhaar_number", models.CharField(max_length=12)),
                ("pan_number", models.CharField(max_length=10)),
                ("dti_ratio", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
