# Generated by Django 4.2.7 on 2026-04-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_applicantprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantprofile",
            name="has_co_applicant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="applicantprofile",
            name="income_variability_high",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="applicantprofile",
            name="risk_flag",
            field=models.CharField(
                choices=[
                    ("LOW", "Low Risk"),
                    ("MEDIUM", "Medium Risk"),
                    ("HIGH", "High Risk"),
                    ("REJECTED", "Rejected"),
                ],
                default="LOW",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="applicantprofile",
            name="salary_bank",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicantprofile",
            name="years_in_business",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="applicantprofile",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("SALARIED_GOVT", "Salaried — Government / PSU"),
                    ("SALARIED_PRIVATE", "Salaried — Private Sector"),
                    (
                        "SELF_EMPLOYED_PROF",
                        "Self-employed Professional (Doctor, CA, Lawyer, Consultant)",
                    ),
                    ("SELF_EMPLOYED_BIZ", "Self-employed Business Owner / Trader"),
                    ("DAILY_WAGE", "Daily Wage / Casual Labourer"),
                    ("FARMER", "Farmer / Agricultural Worker"),
                    ("SEASONAL", "Seasonal Worker"),
                    ("GIG_WORKER", "Gig Worker (Uber, Swiggy, etc.)"),
                    ("PENSIONER", "Pensioner / Retired"),
                    ("HOMEMAKER", "Homemaker"),
                    ("STUDENT_UNEMPLOYED", "Student / Unemployed"),
                    ("NRI", "Non-Resident Indian"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="applicantprofile",
            name="loan_purpose",
            field=models.CharField(
                choices=[
                    ("HOME", "Home Purchase / Renovation"),
                    ("VEHICLE", "Vehicle Purchase"),
                    ("BUSINESS", "Business Expansion"),
                    ("EDUCATION", "Education Loan"),
                    ("MEDICAL", "Medical Emergency"),
                    ("DEBT", "Debt Consolidation"),
                    ("CONSUMER", "Consumer Goods"),
                    ("AGRICULTURE", "Agriculture / Crop Loan"),
                    ("PERSONAL", "Personal Use (Other)"),
                ],
                max_length=100,
            ),
        ),
    ]
