# Generated by Django 4.2.7 on 2026-04-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_applicantprofile_has_co_applicant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
