# Generated by Django 4.2.7 on 2026-04-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_applicantemploymentdocument_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicantemploymentdocument",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("SALARIED_GOVT", "Salaried (Govt/PSU)"),
                    ("SALARIED_PRIVATE", "Salaried (Private)"),
                    ("SELF_EMPLOYED_PROFESSIONAL", "Self-Employed Professional"),
                    ("SELF_EMPLOYED_BUSINESS", "Self-Employed Business"),
                    ("DAILY_WAGE", "Daily Wage Worker"),
                    ("FARMER", "Agricultural / Farmer"),
                    ("SEASONAL", "Seasonal Worker"),
                    ("GIG_WORKER", "Gig Worker"),
                    ("HOMEMAKER", "Homemaker / No Income"),
                    ("STUDENT_UNEMPLOYED", "Unemployed / Student"),
                    ("PENSIONER", "Pensioner"),
                    ("NRI", "NRI (Non-Resident Indian)"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="applicantprofile",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("SALARIED_GOVT", "Salaried (Govt/PSU)"),
                    ("SALARIED_PRIVATE", "Salaried (Private)"),
                    ("SELF_EMPLOYED_PROFESSIONAL", "Self-Employed Professional"),
                    ("SELF_EMPLOYED_BUSINESS", "Self-Employed Business"),
                    ("DAILY_WAGE", "Daily Wage Worker"),
                    ("FARMER", "Agricultural / Farmer"),
                    ("SEASONAL", "Seasonal Worker"),
                    ("GIG_WORKER", "Gig Worker"),
                    ("HOMEMAKER", "Homemaker / No Income"),
                    ("STUDENT_UNEMPLOYED", "Unemployed / Student"),
                    ("PENSIONER", "Pensioner"),
                    ("NRI", "NRI (Non-Resident Indian)"),
                ],
                max_length=50,
            ),
        ),
    ]
