# Generated by Django 4.2.7 on 2026-03-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelMetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=120)),
                ("model_version", models.CharField(default="v1", max_length=40)),
                ("dataset_rows", models.PositiveIntegerField(default=0)),
                ("accuracy", models.FloatField(default=0)),
                ("precision", models.FloatField(default=0)),
                ("recall", models.FloatField(default=0)),
                ("f1_score", models.FloatField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
