# Generated by Django 4.2.7 on 2026-04-01 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_panel", "0003_adminactionlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminactionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("USER_ACCESS", "User access update"),
                    ("OFFICER_ACCESS", "Bank officer management"),
                    ("FRAUD_REVIEW", "Fraud monitoring action"),
                    ("ANNOUNCEMENT", "System announcement"),
                    ("RISK_CONFIG", "Risk rules update"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="RiskConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_decision_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Global toggle for AI-based auto-approval/rejection.",
                    ),
                ),
                (
                    "approval_threshold",
                    models.FloatField(
                        default=0.3,
                        help_text="Applications with risk < this value are auto-approved.",
                    ),
                ),
                (
                    "rejection_threshold",
                    models.FloatField(
                        default=0.6,
                        help_text="Applications with risk > this value are auto-rejected.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Configuration",
                "verbose_name_plural": "Risk Configurations",
            },
        ),
    ]
